### ISSUE TITLE
Activation issue

### ISSUE THREAD

**Issue by tag4lucy** [SebastienDuruz/Eve-ClientsManager#7]
Hello,
I'm looking for a multibox system for eve online which I came across your system. I git cloned on Zorin os and I'm having the following issue. I'm not sure what to do!

thor@thor-MS-7B89:~/Eve-ClientsManager$ python eveclientsmanager/eveclientsmanager.py
  File "eveclientsmanager/eveclientsmanager.py", line 1
SyntaxError: Non-ASCII character '\xc3' in file eveclientsmanager/eveclientsmanager.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by SebastienDuruz** [comment]
Hello,
I didn't touch this project for a long time as I don't play Eve on Linux anymore. I'll check for that error the coming days.
Thanks for the report

**Comment by SebastienDuruz** [comment]
Hello,
It looks like you are missing the **tk** package for python.
After having install the package on your system the application should work correctly.
try to run the following command ==> 
<code>sudo apt install python-tk</code>
